### ISSUE TITLE
Security Update available on 10.10

### ISSUE THREAD

**Issue by jakirkham** [boxcutter/macos#20]
I'm finding there is a security updating I'm missing after running `packer` and `vagrant`. Would it be possible to just install all security updates in `packer`? Does this seem like reasonable behavior to have as default?

**Comment by annawake** [comment]
The easiest way to accomplish this is to run `update.sh` a few more times to get security updates. I've added this in:

https://github.com/boxcutter/macos/commit/6ee23c9c24c6c66af2568ed22dd3b2d3b7c34ad9
