### ISSUE TITLE
Boxcutter hangs at "==> vmware-iso: Waiting for SSH to become available..."

### ISSUE THREAD

**Issue by ap1kenobi** [boxcutter/macos#4]
Running `make` on Yosemite.
Have `Install OS X Yosemite.app` in `iso/OS X Yosemite/` dir.

Fusion comes up but seems to be stuck at boot config screen.
Boxcutter hangs at "==> vmware-iso: Waiting for SSH to become available..."

Here's the full output: https://gist.github.com/ap1kenobi/acb58a8b3b2f8c3cc406

**Comment by sundeer** [comment]
Same here. 
I think what's happening is that our "Install OS X Yosemite.app" is different from the one used by the authors, so the name of the DMG file created from it will different from the one hard-coded into the Makefile.
```
# Makefile
...
MAC_OSX_10_7_LION_BOOT_DMG ?= OSX_InstallESD_10.7.5_11G63.dmg
MAC_OSX_10_8_MOUNTAIN_LION_BOOT_DMG ?= OSX_InstallESD_10.8.5_12F45.dmg
MAC_OSX_10_9_MAVERICKS_BOOT_DMG ?= OSX_InstallESD_10.9_13A603.dmg
MAC_OSX_10_10_YOSEMITE_BOOT_DMG ?= OSX_InstallESD_10.10_14A389.dmg
...
``` 
Look in the ./dmg folder and you'll see your DMG file. In your Makefile.local file put a line like this:
```
# Makefile.local

MAC_OSX_10_10_YOSEMITE_BOOT_DMG := OSX_InstallESD_10.10<YOUR PART>.dmg
```
and rerun `$ make vmware/osx1010[-desktop]`

**Comment by annawake** [comment]
Makefile has been revamped
