### ISSUE TITLE
Make virtualbox/osx109-desktop error

### ISSUE THREAD

**Issue by ducnguyenhuy** [boxcutter/macos#9]
I'm trying to create a Mac OS X Mavericks vagrant box. I downloaded Mac OS X and follow steps here https://stefanscherer.github.io/unboxing-os-x-yosemite-for-packer/ to do that. When I enter "make virtualbox/osx109-desktop". I got an error as below:

Could you please tell me how to fix this error?

Thanks so much.

Error message:
............
...........
created: /Users/abc/Data/Researches/MacOSXBox/osx/dmg/OSX_InstallESD_10.9.5_13F34.dmg
-- Fixing permissions..
-- Checksumming output image..
-- MD5: 1be247dda2f724b6742664ea1a1576e0
-- Done. Built image is located at dmg/OSX_InstallESD_10.9.5_13F34.dmg. Add this iso and its checksum to your template.
rm -rf output-virtualbox-iso
mkdir -p box/virtualbox
packer build -only=virtualbox-iso -var 'cm=nocm' -var 'update=true' -var 'install_xcode_cli_tools=true' -var 'version=1.0.1' -var 'ssh_username=vagrant' -var 'ssh_password=vagrant' -var 'install_vagrant_keys=true' -var "iso_url=dmg/OSX_InstallESD_10.9_13A603.dmg" osx109-desktop.json
virtualbox-iso output will be in this color.

Warnings for build 'virtualbox-iso':

* A checksum type of 'none' was specified. Since ISO files are so big,
a checksum is highly recommended.

==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: file:///dmg/OSX_InstallESD_10.9_13A603.dmg
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Error attaching ISO: VBoxManage error: VBoxManage: error: Could not find file for the medium '/dmg/OSX_InstallESD_10.9_13A603.dmg' (VERR_FILE_NOT_FOUND)
==> virtualbox-iso: VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component Medium, interface IMedium, callee nsISupports
==> virtualbox-iso: VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 178 of file VBoxManageDisk.cpp
==> virtualbox-iso: VBoxManage: error: Invalid UUID or filename "/dmg/OSX_InstallESD_10.9_13A603.dmg"
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error attaching ISO: VBoxManage error: VBoxManage: error: Could not find file for the medium '/dmg/OSX_InstallESD_10.9_13A603.dmg' (VERR_FILE_NOT_FOUND)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component Medium, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 178 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/dmg/OSX_InstallESD_10.9_13A603.dmg"

==> Some builds didn't complete successfully and had errors:
--> virtualbox-iso: Error attaching ISO: VBoxManage error: VBoxManage: error: Could not find file for the medium '/dmg/OSX_InstallESD_10.9_13A603.dmg' (VERR_FILE_NOT_FOUND)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component Medium, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 178 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/dmg/OSX_InstallESD_10.9_13A603.dmg"

==> Builds finished but no artifacts were created.
make: *** [box/virtualbox/osx109-desktop-nocm-1.0.1.box] Error 1

**Comment by StefanScherer** [comment]
@ducnguyenhuy As far as I can see it in your console output you may have to edit the `Makefile` and change the `MAC_OSX_10_9_MAVERICKS_BOOT_DMG` to `OSX_InstallESD_10.9.5_13F34.dmg`. 

The default searches for a 10.9 version.

**Comment by ducnguyenhuy** [comment]
@StefanScherer: I followed your way but then appear an error when installing Mac OS X, I had try 2 times but still got the problem. Then I rename dmg/OSX_InstallESD_10.9.5_13F34.dmg to dmg/OSX_InstallESD_10.9_13A603.dmg and it works now.

Btw, could we give the version number as argument for Make command line? Should it be easier?
